### ISSUE TITLE
Container apps stopped logging console logs to Azure Monitor

### ISSUE THREAD

**Issue by maskati** [microsoft/azure-container-apps#1058] opened 2024-01-24 06:26 UTC
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
ACA apps in in a West Europe environment stopped logging console logs (`ContainerAppConsoleLogs`) to Azure Monitor log destinations between 17th and 23rd January. Different apps stopped logging at different points, 3 apps on 17th, 5 apps on 18th, 6 apps on 23rd. System logs (`ContainerAppSystemLogs`) seem to be logging normally.

Not sure if related to a previous similar issue #988.

**Screenshots**

![image](https://github.com/microsoft/azure-container-apps/assets/21118898/cd0fb52d-3003-4deb-b11d-3c43d337587d)

**Comment by vinisoto** [comment] 2024-01-25 00:50
Hi @maskati, thank you for reaching out. 

Can you please send these details to `acasupport at microsoft dot com` so we can follow up?:

-Subscription Id
-Container App Environment resource id
-Container App name

Thanks!

**Comment by Strandfelt** [comment] 2024-01-25 11:09
> Hi @maskati, thank you for reaching out.
> 
> Can you please send these details to `acasupport at microsoft dot com` so we can follow up?:
> 
> -Subscription Id -Container App Environment resource id -Container App name
> 
> Thanks!

We see the same issue. I will send you a message

**Comment by vinisoto** [comment] 2024-01-25 20:57
hi @Strandfelt and @maskati,

We found a race condition that impacts container apps running in the Consumption workload profile. 

This race condition is triggered whenever there is a change in the Log Destination of the container app environment (e.g., changing from/to "Don't save logs" to "Azure Log Analytics"). This only impacts container apps that already exists in the environment when the Log Destination setting is changed. New container apps are not impacted (e.g., if a container app is created when the Log Destination is already set to Log Analytics, it will continue to send logs work unless the Log Destination setting of the environment is changed).

We finished deploying a hotfix for this this morning. Can you double check if the issue is fixed on your end?.

In some cases, customers might need to change their Container App Environment's Log settings to "Don't save logs" temporarily and them move the setting back to "Azure Log Analytics".

If the issue still persists, we will follow up over email.

Thank you.

**Comment by maskati** [comment] 2024-01-26 09:37
@vinisoto thanks, I am now getting console logs on my apps.

> This race condition is triggered whenever there is a change in the Log Destination of the container app environment

Just as a note, we have performed bicep/arm desired state deployments of the environment, but the actual logging configuration of the environment did not change. It seems this race condition is therefore also triggered by simply overwriting `appLogsConfiguration` with the same value.

**Closed** 2024-01-26 09:37 UTC

**Comment by Strandfelt** [comment] 2024-01-26 13:19
We can confirm that it works on our end now as well

**Comment by tasdflkjweio** [comment] 2024-02-01 19:21
@vinisoto I just recreated this issue. I don't believe it is completely resolved. Yesterday, I changed my container app from using Azure Monitor to Azure Log Analytics and logging continued working. However, I just scaled my app out an hour ago and logs have once again vanished. If useful, the container env + app are running in West US 2 under the Workload - Consumption plan/profile in a private subnet.

**Comment by maythamfahmi** [comment] 2024-02-09 07:11
@vinisoto I have similar issue, not sure what the issue is, log for both Azure Log Analytics and Azure Monitor is unstable, it is hard to describe the issue, but some times it works right a way and some time there is not log. and in most cases I get issue like the one mentioned in https://github.com/microsoft/azure-container-apps/issues/988
