### ISSUE TITLE
az containerapp job stop/starts breaks event-based scaling rules

### ISSUE THREAD

**Issue by Krusty93** [microsoft/azure-container-apps#935] opened 2023-10-11 09:50 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

I have a container app job that I used as GitHub self hosted runner. It works correctly: when an Action requires a self-hosted runner, the job properly scales and complete the job.

The above is true until I execute via CLI the command `az containerapp job stop`; in fact, as soon as I run that command the event-based scaling rule stops to work and everytime I run an Action, I need to manually run `az containerapp job start` command.

The only solution I found is to delete and recreate the job

### Steps to reproduce
1. Create a container app job as explained [in doc](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions)
2. Set the `github-runner` scale rule with these metadata values: [`github_runner: https://api.github.com`; `owner: <your-org>`; `repos: <your-repo>`; `runnerScope: repo`; `targetWorkflowQueueLength: 1`]
3. Run a `self-hosted` GitHub Actions to ensure everything works properly
4. Run via CLI the command `az containerapp job stop -n <your-job> -g <your-rg>`
5. Run the GitHub Actions again

**Expected behavior** [What you expected to happen.]
Job scales properly

**Actual behavior** [What actually happened.]
Job won't scale, you need to manually run `az containerapp job start` 

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by vinisoto** [comment] 2023-10-17 16:41
hi @Krusty93 

We realized that `az containerapp job stop` has the unintended behavior that you described (essentially _disabling_ the Job_).

There are two similar (and confusing) variations of the `az containerapp job stop` command [examples](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-stop(containerapp)-examples):

- `az containerapp job stop` without passing an `execution name`. The original intention if this command was to _stop_ all executions of the Job that are currently running.
- `az containerapp job stop --job-execution-name` passing an `execution name`. This command will stop a specific execution of the Job

If you were trying to simply stop the current execution of the Job, to workaround the current issue, you can obtain all the executions with `az containerapp job execution list` and then call `stop` on the execution that you want to stop.

**Comment by Sankgreall** [comment] 2023-11-01 20:50
I can replicate the original bug here, even when passing `--job-execution-name`. 

From my perspective:

- Job worker executes in response to Event (Azure Queue)
- Job is manually stopped with `az containerapp job stop --job-execution-name {container_name}`
- Queue is cleared 
- New Queue event is submitted
- A new job worker **does not** spawn

I wonder if this is because the Jobs instance doesn't recognise "stopped" workers properly. If this was the case, it would look at the Queue and see 1 event, then look at the container replicas and see 1 (stopped) container, and nothing changes.

**Comment by anandanthony** [comment] 2023-11-11 02:24
We investigated the behavior wherein the event triggered Container App Job stops triggering job executions and found the root cause. A fix for this is in place and should be available across all regions in ~2 weeks.

**Comment by itallackpure** [comment] 2023-12-20 18:03
Is this fixed yet?

**Comment by anandanthony** [comment] 2023-12-21 22:15
Yes, the fix for this has been rolled out.

**Closed** 2024-01-08 15:07 UTC
Labels: bug, In progress, Jobs
