### ISSUE TITLE
How much time it gets to provision a container app with Dapr configurations

### ISSUE THREAD

**Issue by ranjeetkpGit** [microsoft/azure-container-apps#347] opened 2022-08-08 13:26 UTC
How much time it gets to provision a container app with Dapr configurations using bindings.cron to call an API deployed in container app.
It takes few hours to get provisioned. Revision Management windows  showing 'Failed' for hours then gets Provisioned

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.

### Steps to reproduct
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by kendallroden** [comment] 2022-09-14 18:15
This is a duplicate of another issue I believe you made please refer to that issue for follow up

**Closed by kendallroden** 2022-09-14 18:15 UTC
Labels: Needs: triage :mag:
