### ISSUE TITLE
DNS resolution failing for Python gRPC

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-container-apps#45] opened 2021-11-24 21:19 UTC
This is a pretty weird bug, but I'm a bit stumped.  I've been building some samples of calling services over gRPC in different languages.  So far I have [C#](https://github.com/jeffhollan/grpc-sample-dotnet), [go](https://github.com/jeffhollan/grpc-sample-go), and was working on [python](https://github.com/jeffhollan/grpc-sample-python) when I hit this but that only seems to repro for python.  I don't know if it's something with the grpc libraries for python but I figured they call came from the same c++ set of binaries. But regardless, here's the deal.  When I try to call the other gRPC service, I get an error that DNS Resolution failed.  The DNS that fails is the FQDN of the downstream service.

What's strange is when I debug on my local machine (via code or the same container image), the DNS works fine and the gRPC connection works fine.  It's only when the Python container runs in container apps it throws this error. I'm at a bit of a loss.

Steps to repro:
- Deploy the sample solution from here (steps in README) https://github.com/jeffhollan/grpc-sample-python
- Call the https-frontend container at the `/hello` path
- It throws a 500, logs show a DNS resolution failure

Full stack of the DNS error

> 	debug_error_string = "{"created":"@1637787722.745891337","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":1324,"referenced_errors":[{"created":"@1637787722.745888337","description":"DNS resolution failed for service: grpc-backend.internal.gentlemushroom-013cdb8d.canadacentral.azurecontainerapps.io:443","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":359,"grpc_status":14,"referenced_errors":[{"created":"@1637787722.745858136","description":"C-ares status is not ARES_SUCCESS qtype=AAAA name=grpc-backend.internal.gentlemushroom-013cdb8d.canadacentral.azurecontainerapps.io is_balancer=0: DNS server returned answer with no data","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":698,"referenced_errors":[{"created":"@1637787722.740638244","description":"C-ares status is not ARES_SUCCESS qtype=A name=grpc-backend.internal.gentlemushroom-013cdb8d.canadacentral.azurecontainerapps.io is_balancer=0: DNS server returned answer with no data","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":698}]}]}]}"

**Comment by jeffhollan** [comment] 2021-11-24 21:45
Was able to mitigate by adding this environment variable to the container apps environment:

GRPC_DNS_RESOLVER=native

Per this GitHub issue hint from the `c-ares` hint in the stack trace:
https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/environment_variables.md

So something about c-ares DNS resolution isn't happy with Python and Container Apps

**Comment by ahmelsayed** [comment] 2021-12-04 01:08
The root cause for this is https://github.com/coredns/coredns/issues/2389.

**Comment by ahmelsayed** [comment] 2022-01-26 23:45
This should be fixed now. I verified with https://github.com/jeffhollan/grpc-sample-python on Canada Central. The fix is rolling to Europe now.

**Closed by ahmelsayed** 2022-01-26 23:45 UTC
Labels: bug
