### ISSUE TITLE
Roadmap: Configure ingress timeout

### ISSUE THREAD

**Issue by torosent** [microsoft/azure-container-apps#616] opened 2023-02-06 18:02 UTC

**Comment by colinbjohnson** [comment] 2023-06-26 17:35
Is it possible to provide an ETA for this particular roadmap item? We have a project that requires a greater than 240 second timeout that we would _like_ to release on Azure Container Apps instead of utilizing another technology. If the release date was relatively soon (with a week or two of 2023-06-23) we could hold release so that we can release on our preferred platform.

**Comment by dmytro-gokun** [comment] 2023-09-27 13:56
@torosent Is there any update? Is it available as a preview or something?

We've just converted a legacy TCP app to Container Apps and ran into this issue. The worst thing is that this default timeout of 240 seconds is not documented anywhere, so we had to learn this hard way.

**Comment by danielbichuetti** [comment] 2023-10-24 11:42
Hi @dmytro-gokun!

Being able to set an ingress timeout will be a great addition. It's being developed. [Project Roadmap](https://github.com/orgs/microsoft/projects/540).

As a side note, the timeout is properly documented in the [documentation](https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#http) 😸.

**Comment by samcarswell** [comment] 2024-02-13 04:19
Would be great to get an update on the timeline for this feature. This is currently a blocker on using ACA over AKS for us.

**Comment by quality-leftovers** [comment] 2024-02-22 21:39
I'd like to ask if you can provide a bit more information in the documentation regarding what exactly the `Request timeout` refers to?

Is it exactly the same as the envoy [httpconnectionmanager-request-timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-timeout)

```
The amount of time that Envoy will wait for the entire request to be received.
The timer is activated when the request is initiated, and is disarmed when the
last byte of the request is sent upstream (i.e. all decoding filters have processed the request), 
OR when the response is initiated. If not specified or set to 0, this timeout is disabled.
```

**Comment by Miguel-Aguilar-Perez** [comment] 2024-04-02 12:40
Could you please provide an status update on this? when will it be released?

Thanks

**Comment by frederic-saunier** [comment] 2024-05-30 09:32
Same here, could you please provide an ETA on this ?

**Comment by oexos** [comment] 2024-05-31 06:05
240 seconds ingress timeout is still not changeable or configurable as of today I guess. I tried it today and still got 504 Gateway timeout after 4 minutes of connection.

**Comment by Mohsen51** [comment] 2024-06-07 10:26
Any news ? This can be really blocking on some projects...

**Comment by fritzfs** [comment] 2024-06-18 11:02
Any update on this? Thank you!

**Comment by fritzfs** [comment] 2024-09-09 16:18
Same here. I'm doing crazy workarounds with defining Azure ContainerApp Jobs with manual trigger and command override just to resolve one support ticket ... so, yes, please Microsoft, enable configuration on this!

**Comment by simonjj** [comment] 2024-10-25 20:31
closing this as a duplicate of #597

**Closed by simonjj** 2024-10-25 20:31 UTC
Labels: enhancement, roadmap
