### ISSUE TITLE
Provisioning of Container Apps Environment fails quietly when Azure Policies are not passed

### ISSUE THREAD

**Issue by mattharwood** [microsoft/azure-container-apps#381] opened 2022-08-31 08:37 UTC
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When deploying a new Container Apps Environment (in our case, with Pulumi), deployment failed with a ManagedEnvironmentResourceGroupDisallowedByPolicy error[1]. The link with the error takes the user to a generic Container Apps docs page. After investigation, we discovered Azure was creating a Resource Group for the Environment in the background, which did not comply with our Azure policy of requiring tags on each Resource Group. The creation of this Resource Group and its inclusion in Azure Policies seems to be undocumented.

Our only solution to this was to temporarily remove the policy.

[1] _Code="OperationFailed" Message="ErrorCode: ManagedEnvironmentResourceGroupDisallowedByPolicy, Message: Fail to create managed environment because resource group creation is disallowed by policy, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail."_

### Steps to reproduce
1. Add Azure Policy requiring tags on the creation of Resource Groups
2. Attempt to create a Managed Environment through an IaC platform, or when creating a Container App for the first time3. 
3. Receive error and failure 

**Expected behavior** [What you expected to happen.]
Clearer, immediate insight in to why the deployment had failed, and possibly automated remediation.

**Actual behavior** [What actually happened.]
Error given with no appropriate documentation, an automated creation of an undocumented Resource Group failed

**Screenshots**         
N/A

### Additional context
We have replicated this both in the portal and using Pulumi.

**Comment by kendallroden** [comment] 2022-09-14 16:58
I believe we are working on providing more visibility into this - thank you for reporting the request we will reach back out when we have updates

**Comment by kendallroden** [comment] 2022-09-14 18:23
This is a duplicate of https://github.com/microsoft/azure-container-apps/issues/345 please visit for follow up

**Closed by kendallroden** 2022-09-14 18:23 UTC
Labels: Needs: triage :mag:, Provisioning
