### ISSUE TITLE
UnexpectedJob log message for stopped manual job.  

### ISSUE THREAD

**Issue by acollard** [microsoft/azure-container-apps#846] opened 2023-07-20 17:40 UTC
### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A manual job that was stopped is now causing the log entry "Saw a job that the controller did not create or forgot: [redacted]" to show up on each follow up scheduled execution. The manual job was started using an image that doesn't exit so I had to manually stop it.

### Steps to reproduce
1. Create a manual Job using an image that doesn't exit (ex. "mcr.microsoft.com/k8se/quickstart:latest"). 
2. Start job execution using "az containerapp job start". 
3. After 5 min, stop job execution using "az containerapp job stop".
4. Update the image for the job to an image that has a finite run time then exits (mine was 10s).
5. Run the job to completion using "az containerapp job start". 
6. Update triggerType to "Schedule" and set the cron expression to "*/10 * * * *".
7. After a few executions check the execution logs and see the entry "Saw a job that the controller did not create or forgot: [redacted]".

**Expected behavior** [What you expected to happen.]
Stopped jobs should be removed from the controller and not be referenced in future log entries. 

**Actual behavior** [What actually happened.]
The controller continually reports that it forgot about the job in the system logs.

**Screenshots**         
**Job Execution history**
![image](https://github.com/microsoft/azure-container-apps/assets/2044172/7b2d30c9-bd6c-44d4-8627-86bfaf192475)

### Additional context
**ContainerAppSystemLogs_CL entries for the stopped job.**
> "time_t [UTC]","Reason_s","Log_s"
> "7/19/2023, 7:22:24.970 PM",SuccessfulCreate,"Created pod: redacted-dirxxzg-zpr8v"
> "7/19/2023, 7:22:24.976 PM",SuccessfulCreate,"Created pod: redacted-dirxxzg-zpr8v"
> "7/19/2023, 7:22:24.993 PM",AssigningReplica,"Replica 'redacted-dirxxzg-zpr8v' has been scheduled to run on a node."
> "7/19/2023, 7:22:24.999 PM",AssigningReplica,"Replica 'redacted-dirxxzg-zpr8v' has been scheduled to run on a node."
> "7/19/2023, 7:22:25.520 PM",PullingImage,"Pulling image ""mcr.microsoft.com/k8se/quickstart:latest"""
> "7/19/2023, 7:22:25.525 PM",PullingImage,"Pulling image ""mcr.microsoft.com/k8se/quickstart:latest"""
> "7/19/2023, 7:22:26.463 PM",ImagePulled,"Successfully pulled image ""mcr.microsoft.com/k8se/quickstart:latest"" in 948.37701ms (948.381676ms including waiting)"
> "7/19/2023, 7:22:26.468 PM",ImagePulled,"Successfully pulled image ""mcr.microsoft.com/k8se/quickstart:latest"" in 948.37701ms (948.381676ms including waiting)"
> "7/19/2023, 7:22:26.473 PM",ContainerCreated,"Created container redacted"
> "7/19/2023, 7:22:26.565 PM",ContainerStarted,"Started container redacted"
> "7/19/2023, 7:22:26.570 PM",ContainerStarted,"Started container redacted"
> "7/19/2023, 7:27:38.798 PM",StoppingContainer,"Stopping container redacted"
> "7/19/2023, 7:27:38.803 PM",SuccessfulDelete,"Deleted pod: redacted-dirxxzg-zpr8v"
> "7/19/2023, 7:27:38.815 PM",Suspended,"Job suspended"
> "7/19/2023, 7:27:38.820 PM",StoppingContainer,"Stopping container redacted"

**Comment by anandanthony** [comment] 2023-08-30 20:53
We identified the cause for these warnings, fix for this would be available in our next release. ETA 1-2 weeks.

**Comment by vinisoto** [comment] 2023-09-13 19:04
hi, the fix for this is rolled out globally now.

**Closed by vinisoto** 2023-09-13 19:04 UTC
Labels: bug, Jobs
