### ISSUE TITLE
Unable to connect to redis streams using dapr

### ISSUE THREAD

**Issue by joeklin** [microsoft/azure-container-apps#1037] opened 2023-12-18 17:08 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We have started receiving the following error this morning. 

`2023-12-18T16:47:50.527901795Z time="2023-12-18T16:47:50.527836378Z" level=error msg="error occurred while beginning pubsub for topic doselevel_created on component servicebus-pubsub: failed to subscribe to topic sometopic: BUSYGROUP Consumer Group name already exists" app_id=visit instance=dev-visit--v189560-ecso-5dcdb65bf7-gcgh5 scope=dapr.runtime type=log ver=1.11.6`

Glancing at the dapr code indicates that these errors should be ignored. Not sure if there was an update to either dapr or ACA that went out this morning but this appears to have occurred with no application or configuration changes on our side
https://github.com/dapr/components-contrib/blob/323e9bfcfd15931ecef5e10b327e9c01ee868855/pubsub/redis/redis.go#L112

None of our applications can currently sub
### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

**Comment by anbl-jyskebank-dk** [comment] 2023-12-19 12:48
We are seeing the exact same issue - any news on this?

**Comment by berndverst** [comment] 2023-12-19 20:33
Dapr maintainer here. Yes, this is my fault - I hotfixed an issue impacting the Redis component and cherry picked the code you can see in Dapr 1.12 into 1.11.6 to address an issue where the Redis component would create many GBs of logs erroneously (as you can imagine that can get costly for customers). Despite extensive integration tests I could not reproduce the issue you all have encountered.

I'll get things rolled back.

**Comment by chaimtevel** [comment] 2023-12-19 20:36
Thanks!

**Comment by anbl-jyskebank-dk** [comment] 2023-12-19 20:49
Hi Berndverst
Thank you for the quick response to this, mush appreciated :-) 
Funny twist as we are also experiencing the error log problem - I've but an CAP on the log analytics workspace to mitigate this and upgraded the Redis sku (which seems to have minimized the issue).
Will you write when the rollback is done?
Kind Regards

**Comment by berndverst** [comment] 2023-12-19 20:59
Yes I'll provide an update when the rollback is complete.

Though I am not 100% sure whether the rollback can actually address this, or whether the Redis component simply cannot handle restarts on subscription.

I'm perplexed as to why you are seeing this error to begin with!

Here is the relevant code before I made a change:

```go
func (r *redisStreams) Subscribe(ctx context.Context, req pubsub.SubscribeRequest, handler pubsub.Handler) error {
	if r.closed.Load() {
		return errors.New("component is closed")
	}

	err := r.client.XGroupCreateMkStream(ctx, req.Topic, r.clientSettings.ConsumerID, "0")
	// Ignore BUSYGROUP errors
	if err != nil && err.Error() != "BUSYGROUP Consumer Group name already exists" {
		r.logger.Errorf("redis streams: %s", err)
		return err
	}
```
https://github.com/dapr/components-contrib/blob/7b58f89a0235a0df8ae2136283c253b554b3b2bd/pubsub/redis/redis.go#L111-L121

And here is the code now:

```go
func (r *redisStreams) CreateConsumerGroup(ctx context.Context, req pubsub.SubscribeRequest, handler pubsub.Handler) error {
	err := r.client.XGroupCreateMkStream(ctx, req.Topic, r.clientSettings.ConsumerID, "0")
	// Ignore BUSYGROUP errors
	if err != nil && err.Error() != "BUSYGROUP Consumer Group name already exists" {
		r.logger.Errorf("redis streams: %s", err)
		return err
	}
	return nil
}

func (r *redisStreams) Subscribe(ctx context.Context, req pubsub.SubscribeRequest, handler pubsub.Handler) error {
	if r.closed.Load() {
		return errors.New("component is closed")
	}

	if err := r.client.XGroupCreateMkStream(ctx, req.Topic, r.clientSettings.ConsumerID, "0"); err != nil {
		return err
	}
```
https://github.com/berndverst/components-contrib/blob/c5735e1af5ef5eca3ac3733245556d59f23e281c/pubsub/redis/redis.go#L112-L129

This is actually the same code (just refactored into a helper function). The reason being that further into the subscription the helper function is called again (to address the log problem I tried to fix).

As you can see the error `BUSYGROUP Consumer Group name already exists` should never be returned. Neither before my change nor after.

**Comment by anbl-jyskebank-dk** [comment] 2023-12-19 21:10
Hi 
I'm not a Go developer or know the context of the code snippets so keeping that in mind, shouldn't the redeployment check for an existing stream group and simply use the existing one if it exists - not re-throwing an exception?

Kind Regards

**Comment by berndverst** [comment] 2023-12-19 21:27
@anbl-jyskebank-dk this particular Go code has been around since Dapr version 1.1. Well before my time on Dapr (I joined the Dapr open source team at 1.2 release time), and well before there was any Azure offering for Dapr.

The way it is supposed to work is that it is always supposed to create a consumer group, but if the group already exists it will see "BUSYGROUP" from the server. That error should be treated like you mentioned - simply consider the group to already exist and move on. Any other error message should be considered a real error.

For whatever reason however the BUSYGROUP error is being returned here. That should not happen. So I wonder whether the issue is simply `err.Error() != "BUSYGROUP Consumer Group name already exists"`

Instead of rolling back, I believe the right approach might be for me to patch this and make it `!strings.Contains(err.Error(), "BUSYGROUP")` instead.

The way we looked for this response was very server and server version dependent. Looking for this well known command should work.
https://redis.io/commands/xgroup-create/

**Comment by berndverst** [comment] 2023-12-19 21:31
In summary, I don't think I introduced this issue in the cherry-picked hotfix - but rather, the Redis pubsub component code (not written by Azure team members) is error prone, and unfortunately the restart triggered this condition.

My plan is to fix it with another patch looking for `BUSYGROUP` in the way I outlined.

Hope that makes sense to you all. I'm just not confident that a rollback can fix this situation given that the error check and return values did not actually change.

**Comment by anbl-jyskebank-dk** [comment] 2023-12-19 21:32
Sounds like the right solution - the contains method must be more robust :-)

Again - thank you and the team for all your work ;-)

**Comment by berndverst** [comment] 2023-12-19 22:20
I found the issue. See the second code snippet? It isn't supposed to use the `XGroupCreateMkStream` function anymore. It's supposed to use the helper function `CreateConsumerGroup`.

I forgot to cherry-pick another commit that actually switched this. And unfortunately I don't have integration tests which already had an existing consumer group / stream in place or else I would have found this.

Getting this fixed up right now.

**Comment by berndverst** [comment] 2023-12-19 23:08
The new sidecar image `v1.11.6-msft.6` is currently building. Once this is ready I am coordinating the process of getting this rolled out to you all as soon as possible.

If you are curious, the contents of the fixup patch are here: https://github.com/berndverst/components-contrib/pull/4/files

(This is a dummy PR I used to generate the patch file)

**Comment by joeklin** [comment] 2023-12-20 14:26
Thanks @berndverst! I was equally confused because, at first glance, the code didn't seem to allow that error to leak through. Can you let us know when its officially rolled out in ACA? We've had to swap out Redis for another component for the time being (kudos to dapr for making this relatively painless) and I'd like to test this out and confirm the fix before swapping back.

**Comment by berndverst** [comment] 2023-12-20 22:49
The fix has been rolling out since yesterday, but it takes a few days to make it to all of our production regions.

However, a member of the Container Apps engineering team will manually upgrade individual Container Apps environments where we have found the "BUSYGROUP" log message within the past several days. This upgrade should occur within the next 12 hours or so. I will post again once I have heard that this is complete.

**Comment by anbl-jyskebank-dk** [comment] 2023-12-21 13:54
Hi Berndverst

It works for us today - thank you.

Kind Regards
Anders

**Comment by greenie-msft** [comment] 2023-12-21 21:19
Closing as this issue has been resolved.

**Closed by greenie-msft** 2023-12-21 21:19 UTC
Labels: Dapr
