### ISSUE TITLE
Pub/Sub component with Session enabled Azure Service Bus Topics do not deliver messages in sequence

### ISSUE THREAD

**Issue by jpiquot** [microsoft/azure-container-apps#1041] opened 2023-12-20 09:05 UTC
## Expected Behavior

When sessions are enabled, a Pub/Sub component subscription should receive messages in sequential order.

![image](https://github.com/microsoft/azure-container-apps/assets/6775094/2f610550-35cc-40f6-be17-802bfb2da11f)

## Actual Behavior

Messages are being received out of sequence, with the next message arriving before the previous one has been received.

![image](https://github.com/dapr/components-contrib/assets/6775094/98864be6-5fcf-41b2-89fd-974bf13ec85d)

## Steps to Reproduce the Problem

- Create a DAPR enabled Azure Container App application.
- Configure a pub/sub component to connect to an Azure Service Bus Topic.

```
[ApiController]
public class PartiesCommandsController(
    ConventionNamingCommandProcessor commandProcessor,
    IHostEnvironment hostEnvironment,
    ILogger<PartiesCommandsController> logger) : CommandSubmissionController(commandProcessor, hostEnvironment, logger)
{
    /// <summary>
    /// Handle external systems commands as an asynchronous operation.
    /// </summary>
    /// <param name="commandState">State of the command.</param>
    /// <returns>A Task&lt;ActionResult&gt; representing the asynchronous operation.</returns>
    [CustomerCommandsBusTopic]
    [TopicMetadata("requireSessions", "true")]
    [TopicMetadata("sessionIdleTimeoutInSec ", "2")]
    [TopicMetadata("maxConcurrentSessions", "8")]
    [HttpPost("/handle-customer-commands")]
    public async Task<ActionResult> SubmitCustomerCommandsAsync(CommandState commandState)
        => await HandleCommandAsync(
                commandState,
                Customer.GetAggregateName(),
                CancellationToken.None)
            .ConfigureAwait(false);
}
```
I observe the below setup, but it appears to be globally applied to the topic. This configuration might not support concurrent session handling if it is set to 1.

> - maxActiveMessages : Defines the maximum number of messages to be processing or in the buffer at once. This should be at least as big as the maximum concurrent handlers. 
> - maxConcurrentHandlers : Defines the maximum number of concurrent message handlers.

![image](https://github.com/microsoft/azure-container-apps/assets/6775094/daa901db-ce00-468b-9b1a-6ba03c715562)

## Release Note
Fix session enabled topics should send messages in sequence

**Comment by berndverst** [comment] 2023-12-20 19:23
This is a duplicate of https://github.com/dapr/components-contrib/issues/3281. Only the issue in Dapr OSS needs to exist.

- Bernd (Dapr Maintainer)

**Comment by berndverst** [comment] 2023-12-20 19:43
I provided an explanation on the linked issue and will keep all communication there as this issue is not a Container Apps issue - and it is currently expected Dapr behavior.

Each sidecar has no awareness of sessions being processed by another sidecar. Dapr does not support coordinating this across sidecars. As such when using multiple sidecars ordering cannot be guaranteed for sessions.

Let's keep any discussion on https://github.com/dapr/components-contrib/issues/3281.

This issue here can be closed.

**Closed** 2023-12-21 05:09 UTC
Labels: Needs: triage :mag:
