### ISSUE TITLE
Feature Request: Access to KeyVault/Managed Identity

### ISSUE THREAD

**Issue by Maggern3** [microsoft/azure-container-apps#151] opened 2022-03-29 10:44 UTC
**Is your feature request related to a problem? Please describe**.  
Can't access KeyVault because Azure Container Apps does not have support for managed identity.

**Describe the solution you'd like**.    
Add managed identity to Azure Container Apps.

**Describe alternatives you've considered**.   
Some kind of integration with the native secrets store in ACA and Azure KeyVault. Or other approach to access the KeyVault.

**Comment by anthonychu** [comment] 2022-03-29 15:00
Basic managed identity support is coming to Container Apps in April. Both system and user managed identities will be supported and can be used from your application to authenticate with services, including Key Vault. We'll look into deeper Key Vault integration in the future.

#16

**Comment by SteveB-UBS** [comment] 2022-03-30 13:33
Would this be available in private preview asap?

**Comment by kendallroden** [comment] 2022-09-14 22:32
Duplicate of https://github.com/microsoft/azure-container-apps/issues/7

**Closed by kendallroden** 2022-09-14 22:32 UTC
Labels: enhancement
