### ISSUE TITLE
Unable to deploy with empty secret

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#660] opened 2023-03-08 16:22 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I had a secret on an application which I no longer needed. Since past revisions used the secret, I could not remove it, so I blanked it out during an ACA BICEP deployment, today when I went to make a new deployment, ACA started complaining

![image](https://user-images.githubusercontent.com/969938/223768653-2aecc5f8-ddfb-4dac-9c6d-71078799fd75.png)

So I went to try to remove the secret entirely, but I cant do that either, when I try to remove the secret I get:

(WebhookInvalidParameterValue) The following field(s) are either invalid or missing. Invalid value: "tag-9051c7c": revision with suffix tag-9051c7c already exists.: template.revisionsuffix.

### Steps to reproduce
1. Create an app with a secret, specifying rev suffix
2. Blank the secret out (cant remove it since older rev is using it)
3. Create a new rev not using the secret, specifying rev suffix
4. Try to remove the secret  (fails)
5. Try to add a new app (fails)

**Expected behavior** [What you expected to happen.]
You should be able to remove secrets even if they're referenced by previous revisions (just return empty string to apps which request it), you should also be able to deploy apps even if secrets or environment variables are empty ("")

**Actual behavior** [What actually happened.]
Multiple errors, both while attempting to deploy a new revision

**Screenshots**         

### Additional context
Workaround is to remove the secret in bicep once no other revisions are referencing the secret, requiring phases of deployments

**Comment by krmapowel** [comment] 2023-03-09 08:20
I'm pretty sure it is duplicate of the issue I've opened few days ago
https://github.com/microsoft/azure-container-apps/issues/654

**Comment by simonjj** [comment] 2024-08-08 22:49
Closing this, as it is essentially a duplicate of #654. Issue might still exists and we need to validate it indeed.

**Closed by simonjj** 2024-08-08 22:49 UTC
Labels: Storage, Needs: Validation
