### ISSUE TITLE
Feature Request: Have policy tags automatically applied to the managed resource groups during Container App creation 

### ISSUE THREAD

**Issue by ractando** [microsoft/azure-container-apps#338] opened 2022-08-03 12:15 UTC
**Is your feature request related to a problem? Please describe**.  
During the creation of a Container App, a default Resource Group is created with the prefix MC_. There is a policy on the subscription which restricts the creation of a new Resource Group without some/a specific tag. As this is a Managed Resource, we do not have any ownership on it, and as the RG does not have the tag, the Container App creation ultimately fails.

**Describe the solution you'd like**.    
Have policy tags automatically applied to the managed resource groups during Container App creation 

**Describe alternatives you've considered**.   
The workaround tried was to add an exception for the resource groups that have the MC_ prefix, and _region suffix on the Policy.

**Comment by kendallroden** [comment] 2022-09-14 18:26
Duplicate of https://github.com/microsoft/azure-container-apps/issues/345 please refer to that issue for updates

**Closed by kendallroden** 2022-09-14 18:26 UTC
Labels: duplicate
