### ISSUE TITLE
Documentation on outbound NSG rules not entirely accurate?

### ISSUE THREAD

**Issue by BrianRosamilia** [microsoft/azure-container-apps#619] opened 2023-02-09 22:03 UTC
### This issue is a:
- [ ] bug report -> please search issues before submitting
- [X] documentation issue 
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Implementing the outbound security rules to lock down a container app to not be able to make outbound internet requests seems to not allow them to fully engage with the control plane/host

There must be more required rules than what are marked as `Required` in this document https://learn.microsoft.com/en-us/azure/container-apps/firewall-integration#outbound-with-servicetags

The documentation seems to say that your app will work if you set a rule like this

Outbound Allow `AzureCloud.<REGION>` ports 1194 and 9000 (any protocol)

Your app will work and you will block all outbound traffic, but there seems to be an issue with this.

### Steps to reproduce
1. Deploy a hello world web app to azure container apps
2. Set all of the `Required` NSG outgoing rules with the highest priority, per the documentation
3. Set a deny all internet traffic rule with lower priority than the above
4. The container app will never respond to the HTTP request, eventually responding `stream timeout`.

**Expected behavior** [What you expected to happen.]
1. The container app will be available for requests

**Actual behavior** [What actually happened.]
1. `stream timeout` response after ~3 minutes

**Screenshots**     

The below **does** work. Which makes me think that some of the 'Outbound with wild card IP rules' are required despite not being marked as such.  I didn't test further than opening the region up for outbound traffic after that worked, but I'm hoping to find out the exact requirements for this.

![image](https://user-images.githubusercontent.com/4909591/217948690-c88f55c9-1904-4137-858c-84b85b4f40dd.png)

**Comment by BrianRosamilia** [comment] 2023-02-20 04:31
Actually I made a mistake in my initial comment--those outbound NSG rules only work if you add them after successfully deploying your container app(s).

If you try to first deploy them with the outbound rule on the NSG of the infrastructure subnet, you get this

`Code="OperationFailed" Message="ErrorCode: ManagedEnvironmentConnectionBlocked, Message: Fail to create managed environment because outbound connectivity was blocked, refer to https://go.microsoft.com/fwlink/?linkid=2198255 for more detail."`

The reason I got past this the first time is probably because whatever is doing this needs outbound connectivity on the container app creation by the environment.

Even setting my NSG outbound rule to allow `AzureCloud` on any port and any address, it still won't work.  So something must be wrong here.

**Comment by Sharmagowtham709** [comment] 2023-03-04 05:26
This is being weird! If there are multiple organization handling the landing zone and the infra for applications, how would they co-ordinate in such scenario. I think azure ca support has to look into this and sort this out, as soon as possible.

**Comment by RemyRemRoyal** [comment] 2023-05-05 17:20
Also experiencing strange behavior with NSGs while allowing the ports to service tags listed in documentation.
ALB inbound rule:
![image](https://user-images.githubusercontent.com/57540567/236524135-128b3838-5d25-44e1-ac5d-a469add82b4d.png)

Outbound rules:

![image](https://user-images.githubusercontent.com/57540567/236524386-4aafd662-4b13-48c6-823a-24823a9dd8a3.png)

CAE error:
![image](https://user-images.githubusercontent.com/57540567/236524481-4de35d12-fae0-4e02-847f-5057f4348968.png)

**Comment by xaviermignot** [comment] 2023-05-31 22:13
Hi, I'm facing the same problem and the only place on the Internet this error is mentionned is on this issue.
I have one environment where the creation of the Container App/Env succeeds with the same NSG rules as mentionned in the previous comments.

On another environment I have the same error as everyone here. There are several differences in this environment and I have made several tests (disassociate route table, even disassociate the NSG) but it still doesn't work. I have noticed custom DNS servers on the VNET, I'm wondering if it could be the cause in my case, maybe the managed API is not properly resolved ?

So I would like to know if I can get the hostname the service is trying to reach when creating the CAE. 
If yes I could check if it's properly resolved by the custom DNS.

Many thanks !

**Comment by BrianRosamilia** [comment] 2023-05-31 22:39
It would be great to get an update and possibly a timeframe.  I would really like to use this.  I'm actually kind of surprised only a few people have tried setting up outbound rules that block internet access.

I never like pinging people in issues.  But at this point, I'm not sure this has been looked at since I made my initial comments which I was somewhat unconfident in (I said it was a documentation issue but it looks like an issue with the service).  

I am now feeling pretty confident! So, @cachai2 is there any update you could possibly share? :) (appreciate what Azure has done with container apps btw).  And feel free to revise the title of this issue.

**Comment by xaviermignot** [comment] 2023-06-02 01:32
Well, I finally managed to create an internal CAE, and now that I have a better understanding of my issue I can tell it's not the same as in the original comment, sorry.

I do not try to block outbound internet connectivity in my case, I still have the `AllowInternetOutBound` rule enabled on my NSG... My problem was the custom DNS as I had suspected, so I did sort it out with the following actions:
- Removing the route table association with my NSG as it's not supported by consumption environment as described [here](https://learn.microsoft.com/en-us/azure/container-apps/networking#routes)
- Adding the `168.63.129.16` address as a forwarder in the custom DNS servers as suggested [here](https://learn.microsoft.com/en-us/azure/container-apps/networking#dns) 

And then it finally worked \o/ 

I know this does not solve the original issue but I share my solution if anyone stumbles upon this issue as I did yesterday.

**Comment by RemyRemRoyal** [comment] 2023-06-12 21:46
> Well, I finally managed to create an internal CAE, and now that I have a better understanding of my issue I can tell it's not the same as in the original comment, sorry.
> 
> I do not try to block outbound internet connectivity in my case, I still have the `AllowInternetOutBound` rule enabled on my NSG... My problem was the custom DNS as I had suspected, so I did sort it out with the following actions:
> 
> * Removing the route table association with my NSG as it's not supported by consumption environment as described [here](https://learn.microsoft.com/en-us/azure/container-apps/networking#routes)
> * Adding the `168.63.129.16` address as a forwarder in the custom DNS servers as suggested [here](https://learn.microsoft.com/en-us/azure/container-apps/networking#dns)
> 
> And then it finally worked \o/
> 
> I know this does not solve the original issue but I share my solution if anyone stumbles upon this issue as I did yesterday.

This may have been my issue as well. I ended up removing Custom DNS for other reasons to fix another issue. I did have a long support case with MSFT explaining that even if you have the forwarder added into the Custom DNS settings it will still attempt to validate DNS against your internal DNS servers. Without forward lookup zones it will return NXdomain without proceeding a check against the MSFT DNS forwarder. This was for a private DNS related issue when trying to connect a CA to a private MySQL instance so hopefully that helps someone :)

**Comment by xaviermignot** [comment] 2023-06-14 22:16
@cachai2 I was using a Consumption-only environment.

**Comment by DevMan01** [comment] 2023-06-15 02:53
This was my issue too. Tried to create the CAE and it kept giving me this error. The fix was removing custom DNS (even though it is forwarding) and using Azure Default DNS.

**Comment by y-luis-rojo** [comment] 2023-08-31 17:44
> @BrianRosamilia and folks, thank you for all the feedback. We'll be investigating this. Can you please share if your Container Apps are on Consumption only environments or workload profiles environments?

Same issue here. Using Consumption only environment.

**Comment by cachai2** [comment] 2024-04-24 20:37
Closing this issue as NSG documentation was updated a while back, and there have been no additional comments on this issue.

**Closed by cachai2** 2024-04-24 20:37 UTC
Labels: documentation, Networking, Needs: Investigation
