### ISSUE TITLE
Aspire Dashboard: Could not authenticate user with requested resource.

### ISSUE THREAD

**Issue by aitrailblazer** [microsoft/azure-container-apps#1231] opened 2024-07-13 16:05 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

I'm following:
See live data on Azure Container Apps with the Aspire dashboard
https://techcommunity.microsoft.com/t5/apps-on-azure-blog/see-live-data-on-azure-container-apps-with-the-aspire-dashboard/ba-p/4147938

Troubleshooting
You may receive an authentication error when accessing the dashboard – “Could not authenticate user with requested resource.”
To solve this problem, ensure you have been granted "Microsoft.App/managedEnvironments/write", "Contributor", or "Owner" on the container app environment resource.

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm following the instructions in assigning Contributor, Owner role

but received :

Could not authenticate user with requested resource.

### Steps to reproduce
1) Deploy a .NET Aspire project to Azure Container Apps
https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment
2) Quickstart: Build your first .NET Aspire project
https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-your-first-aspire-app?pivots=dotnet-cli

Granted Owner status for the 
Container Apps Environment

**Expected behavior** [What you expected to happen.]

to be able to view the dashboard.

**Actual behavior** [What actually happened.]
Could not authenticate user with requested resource.

**Comment by snehapar9** [comment] 2024-07-16 00:01
Thanks for opening this issue @aitrailblazer! Can you please confirm if you have `Write` permission on your container app environment?

**Comment by Fazer01** [comment] 2024-07-16 14:50
Following this. Having the same issue here. 

@snehapar9 How to verify "Microsoft.App/managedEnvironments/write" permission? We only have the ability to set Owner / Contributor via RBAC.

Regards,

**Comment by aitrailblazer** [comment] 2024-07-16 20:56
Please elaborate with step by step

**Comment by snehapar9** [comment] 2024-07-16 23:19
@Fazer01 Owner/Contributor should have Write permissions. 
Can you please share your environment name and subscription Id to acasupport@microsoft.com? We will take a closer look.

**Comment by snehapar9** [comment] 2024-07-17 00:24
@aitrailblazer Thanks for emailing ACA Support. We performed mitigation steps on your environment. Can you re-try and let us know if you can access the Dashboard?

**Comment by aitrailblazer** [comment] 2024-07-17 03:05
Dear Aspire support,

I confirm I can access the dashboard now.

I had to add
https://webfrontend--jodu2oa.greenocean-c239bb24.westus3.azurecontainerapps.io/.auth/login/aad/callback
in my App Registration. I have my domain
https://dev.aitrailblazer.app/
it would  be good if I can access the dashboard via this domain.
For future reference I would like to know how to configure it myself.

Speaking of my App Registration I configured Microsoft Identity but I lost all interactivity and also
this:
***@***.***


I followed:

https://learn.microsoft.com/en-us/training/modules/create-aspire-applications/learn-how-create-new-aspire-application

I like aspire very much and I would like to have Authorization.

Much better if I can do this:

Overview - External ID in external tenants - Microsoft Entra External ID | Microsoft Learn<https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam>
Secure your apps using External ID in an external tenant


***@***.***

From: snehapar9 ***@***.***>
Date: Tuesday, July 16, 2024 at 5:24 PM
To: microsoft/azure-container-apps ***@***.***>
Cc: Constantine ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/azure-container-apps] Aspire Dashboard: Could not authenticate user with requested resource. (Issue #1231)

@aitrailblazer<https://github.com/aitrailblazer> Thanks for emailing ACA Support. We performed mitigation steps on your environment. Can you re-try and let us know if you can access the Dashboard?

**Comment by umnex** [comment] 2024-07-17 18:53
I'm having the same issue. Cannot access dashboard after granting both "Owner" & "Contributor" roles to my account. Please note that my account is a guest in this azure tenant.

**Comment by umnex** [comment] 2024-07-17 18:53
getting error: "Could not authenticate user with requested resource."

**Comment by umnex** [comment] 2024-07-18 10:25
hi, any help would be appreciated. still getting the same error.

**Comment by snehapar9** [comment] 2024-07-18 22:01
@umnex performed mitigation on your environment. Please confirm if you can access the dashboard.

**Comment by aitrailblazer** [comment] 2024-07-18 22:11
I tested it and received an error: Access was denied

**Comment by snehapar9** [comment] 2024-07-19 07:25
@aitrailblazer  can you please share more details?Are you seeing a 403?

**Comment by aitrailblazer** [comment] 2024-07-19 16:50
The message was:

You are not authorized to view ....

Now it is OK:

<img width="961" alt="image" src="https://github.com/user-attachments/assets/8770ed78-062a-4dda-8758-bced550653ab">

But there is another issue:

I added Microsoft Entra External ID:
Socket connectivity is not working
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/3d98972d-fc70-42c3-939c-6a51c3487ddc">

Interactivity is not working
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/a4607c58-f17a-4258-ae2f-e122fffe0146">

**Comment by anthonychu** [comment] 2024-07-19 23:49
The websocket + auth error is likely unrelated to the Aspire dashboard authentication issues in this thread and we can track it separately at #1236

**Comment by 9hsein5** [comment] 2024-07-20 12:25
I am having the same issue, since yesterday @snehapar9

**Comment by iturner100** [comment] 2024-07-21 22:58
I'm also getting the 403 when trying to access the dashboard.

I'm seeing it both within an environment running my own applications (blazor web, .net 8 api) as well an environment running the quick-start hello world image.

I have owner rights on the subscription the container apps and environments are in

**Comment by MrDeej** [comment] 2024-07-22 12:21
I have same issues, 403 on all my dashboards, so right now I am blind to my logs.

Tried app registration fix described over with both:
https://aspire-dashboard.ext.{azure resource name}.norwayeast.azurecontainerapps.io/.auth/login/aad/callback
https://aspire-dashboard.ext.{azure resource name}.norwayeast.azurecontainerapps.io/signin-oidc

But no success

**Comment by umnex** [comment] 2024-07-22 18:41
I think the aspire dashboard should be deployed as a separate independent resource within the resource group so that we can manage all of its aspects on our own.

**Comment by umnex** [comment] 2024-07-22 18:44
I'm still unable to access the dashboard in 2 different environments.

**Comment by jedjohan** [comment] 2024-07-22 20:18
> I think the aspire dashboard should be deployed as a separate independent resource within the resource group so that we can manage all of its aspects on our own.

That sounds like a great idea !

**Comment by MrDeej** [comment] 2024-07-22 21:44
@davidfowl I think your orchestration is broken. I got 403 Dashboard on a freshly new Aspire Starter kit when deployed with azd.

**Comment by umnex** [comment] 2024-07-23 10:20
Can we please get an update on this? when can we expect this issue to be resolved?

**Comment by chosh-capa** [comment] 2024-07-23 11:13
same here

**Comment by bbowers0** [comment] 2024-07-23 12:20
I'm having this same issue in two different accounts/subscriptions.

**Comment by MrDeej** [comment] 2024-07-24 12:27
Up and running again today. I did nothing. Magical.

**Comment by bbowers0** [comment] 2024-07-24 21:08
The dashboard works if I launch it in an InPrivate or Incognito window so that it prompts me to sign in.  This worked for a work Microsoft account.  The sign in UI for the dashboard doesn't allow me to specify whether it's a work or personal account and it just picks the work account, so I can't view the dashboard associated with my personal Microsoft account.

**Comment by aitrailblazer** [comment] 2024-07-25 00:16
this and the issues that Aspire cannot work with External ID and native authentication is making it not GA and no usable right now. There is a long way till GA.

**Comment by simonjj** [comment] 2024-07-26 17:41
We have a fix for the original parent issue raised. We will be rolling this into the fleet over the coming weeks. Until this is fix is available everywhere. Please send an email to acasupport and reference this issue for us to reconcile this for you manually.

**Comment by simonjj** [comment] 2024-07-26 17:49
To additionally clarify the 403 issue mentioned in the comments is unrelated to the parent issue and is being tracked in #1238

**Comment by MrDeej** [comment] 2024-07-29 10:53
![image](https://github.com/user-attachments/assets/bbe1ce88-70cf-4580-8383-3344276103d3)
I am so tired of seeing this page instead of my highly valued logs and traces. Can you please fix whatever that is wrong?

**Comment by ijn-kruso** [comment] 2024-08-01 12:45
I'm having the same issues. I have Contributor role for the Container App.

**Comment by snehapar9** [comment] 2024-08-02 18:13
The fix for this issue has been rolled out. Please let us know if you continue to encounter this error.

**Comment by snehapar9** [comment] 2024-08-02 18:24
> I'm having the same issues. I have Contributor role for the Container App.

@ijn-kruso can you please confirm if you have Contributor/Owner permission on the Container App environment?

**Comment by ijn-kruso** [comment] 2024-08-06 07:13
> > I'm having the same issues. I have Contributor role for the Container App.
> 
> @ijn-kruso can you please confirm you have Contributor/Owner permission on the Container App environment?

Just checked - and I'm Contributor on the Container App Environment as well, and still, getting the same error:
_Could not authenticate user with requested resource._

![image](https://github.com/user-attachments/assets/cf9b7e88-d753-4754-83b9-9f99ad5ffa10)

**Comment by ijn-kruso** [comment] 2024-08-12 08:49
> > > I'm having the same issues. I have Contributor role for the Container App.
> > 
> > 
> > @ijn-kruso can you please confirm you have Contributor/Owner permission on the Container App environment?
> 
> Just checked - and I'm Contributor on the Container App Environment as well, and still, getting the same error: _Could not authenticate user with requested resource._
> 
> ![image](https://private-user-images.githubusercontent.com/83574335/355348858-cf9b7e88-d753-4754-83b9-9f99ad5ffa10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTI2NzcsIm5iZiI6MTcyMzQ1MjM3NywicGF0aCI6Ii84MzU3NDMzNS8zNTUzNDg4NTgtY2Y5YjdlODgtZDc1My00NzU0LTgzYjktOWY5OWFkNWZmYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4NDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZWYxZDUxZDAyMGUxMTIxMjkyZDFiOWU2ODk1MDE3NjZlZTMyNjhiOTBhY2Y4M2U4NjNjMGQ0MDY1YTQ5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wcvgv8kHLDi8lCjw05T7e5hEq0XYmc-JJkJ7ZYpp-Wg)

FYI @snehapar9 Still having this issue as of today.

**Comment by bishwaranjans** [comment] 2024-08-12 09:19
It is the same issue for me. Could not authenticate user with requested resource.

**Comment by snehapar9** [comment] 2024-08-13 17:51
Hey @ijn-kruso can you please confirm you followed outlined [here](https://github.com/microsoft/azure-container-apps/issues/1238#issuecomment-2284594699)

**Comment by snehapar9** [comment] 2024-08-13 17:55
@bishwaranjans you mentioned you were able to access the dashboard after you modified permissions on the environment level?
Are you still seeing this error?

**Comment by ijn-kruso** [comment] 2024-08-16 08:05
> Hey @ijn-kruso can you please confirm you followed steps outlined [here](https://github.com/microsoft/azure-container-apps/issues/1238#issuecomment-2284594699)? You need to have Owner/Contributor access on the container app environment. Please note that permissions from subscription/resource group do not propagate.
> 
> Can you please provide your environment name and subscription id to [acasupport@microsoft.com](mailto:acasupport@microsoft.com)? Please be sure to link this issue.

I can confirm i have Contributor access. When i go to the Container Environment -> Access control (IAM) -> View my Access.
![image](https://github.com/user-attachments/assets/5c70a098-fdc2-40df-af9c-a05ac1011767)

To confirm, from what you're saying, Contributor is not enough when it's Inherited from Resource Group? Is this intended? We need to manually add Contributor directly on the Container Environment?

**Comment by snehapar9** [comment] 2024-08-20 01:55
> > Hey @ijn-kruso can you please confirm you followed steps outlined [here](https://github.com/microsoft/azure-container-apps/issues/1238#issuecomment-2284594699)? You need to have Owner/Contributor access on the container app environment. Please note that permissions from subscription/resource group do not propagate.
> > Can you please provide your environment name and subscription id to [acasupport@microsoft.com](mailto:acasupport@microsoft.com)? Please be sure to link this issue.
> 
> I can confirm i have Contributor access. When i go to the Container Environment -> Access control (IAM) -> View my Access. ![image](https://private-user-images.githubusercontent.com/83574335/358514180-5c70a098-fdc2-40df-af9c-a05ac1011767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTg5NzEsIm5iZiI6MTcyNDExODY3MSwicGF0aCI6Ii84MzU3NDMzNS8zNTg1MTQxODAtNWM3MGEwOTgtZmRjMi00MGRmLWFmOWMtYTA1YWMxMDExNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAxNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NmUxZTQzYTA2OTIxYjg3MWExZGM2ZTdiYzg0NTIzOTliYzExMDI0MzMwODM1ZGY4NTAzZjgzOTE1MzZjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.axIGrGrqXGJslOqrYCgTsrYpuCnCs6Nv4ZSlLL6LMRs)
> 
> To confirm, from what you're saying, Contributor is not enough when it's Inherited from Resource Group? Is this intended? We need to manually add Contributor directly on the Container Environment?

@ijn-kruso correct. we are working on rolling out fix for inherited permissions from resource group to be propagated properly.

**Comment by simonjj** [comment] 2024-08-22 23:03
Fix should be available and rolled out now. Please open a new issue if this should come back up.

**Closed by simonjj** 2024-08-22 23:03 UTC
Labels: dotnet-aspire

**Comment by ijn-kruso** [comment] 2024-08-23 07:01
> > > Hey @ijn-kruso can you please confirm you followed steps outlined [here](https://github.com/microsoft/azure-container-apps/issues/1238#issuecomment-2284594699)? You need to have Owner/Contributor access on the container app environment. Please note that permissions from subscription/resource group do not propagate.
> > > Can you please provide your environment name and subscription id to [acasupport@microsoft.com](mailto:acasupport@microsoft.com)? Please be sure to link this issue.
> > 
> > 
> > I can confirm i have Contributor access. When i go to the Container Environment -> Access control (IAM) -> View my Access. ![image](https://private-user-images.githubusercontent.com/83574335/358514180-5c70a098-fdc2-40df-af9c-a05ac1011767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMTg5NzEsIm5iZiI6MTcyNDExODY3MSwicGF0aCI6Ii84MzU3NDMzNS8zNTg1MTQxODAtNWM3MGEwOTgtZmRjMi00MGRmLWFmOWMtYTA1YWMxMDExNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAxNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NmUxZTQzYTA2OTIxYjg3MWExZGM2ZTdiYzg0NTIzOTliYzExMDI0MzMwODM1ZGY4NTAzZjgzOTE1MzZjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.axIGrGrqXGJslOqrYCgTsrYpuCnCs6Nv4ZSlLL6LMRs)
> > To confirm, from what you're saying, Contributor is not enough when it's Inherited from Resource Group? Is this intended? We need to manually add Contributor directly on the Container Environment?
> 
> @ijn-kruso correct. we are working on rolling out a fix for inherited permissions from resource group to be propagated properly.

@snehapar9 
I'm working as a consultant and getting new permissions added can be a lengthy process. Can you update the ticket once the "inherited permissions fix" is available?

**Comment by snehapar9** [comment] 2024-08-23 16:50
@ijn-kruso sure, I will. Thanks!

**Comment by aitrailblazer** [comment] 2024-09-22 20:02
I tested today.

the dashboard is working:
https://aspire-dashboard.ext.<name>-12ab3456.eastus2.azurecontainerapps.io/

this is the working link for the web app:
https://webfrontend.<name>-12ab3456.eastus2.azurecontainerapps.io

When I click on the web app link from the dashboard:
the link is not correct:
https://webfrontend--c6gmgnh.<name>-12ab3456.eastus2.azurecontainerapps.io/

I see --c6gmgnh. which is not correct.

From other side logs are OK.

**Comment by dluc** [comment] 2025-07-02 22:24
From: https://learn.microsoft.com/en-us/azure/container-apps/aspire-dashboard?pivots=azd#troubleshooting

> make sure you **explicitly give yourself a Contributor** or Owner **role on your Container Apps environment**.

tested it today as I was hitting the same issue.

**Comment by BOBx5** [comment] 2026-01-22 03:34
I was able to access Aspire dashboard when I have `Contributor` role explicitly, not by inherited either by _Subscription_,  _ResourceGroup_ or _Group(Memeber)_.
