### ISSUE TITLE
Feature Request: Add support for KEDA scalers to authenticate with RBAC

### ISSUE THREAD

**Issue by onionhammer** [microsoft/azure-container-apps#535] opened 2022-12-19 21:01 UTC
Currently it appears that azure-based KEDA scalers such as 'azure-queue' must use connection strings

https://github.com/Azure/reddog-containerapps/blob/main/deploy/bicep/modules/container-apps/accounting-service.bicep#L78

The schema's auth settings only appear to allow for secretRefs, but no way to configure a managed client id, like you can with Kubenetes hosted keda scalers (https://keda.sh/docs/2.8/scalers/azure-storage-queue/#example)

**Comment by anthonychu** [comment] 2023-01-13 21:50
This is currently under investigation but there's no ETA yet. (internal tracking 16438034)

**Comment by motasem13** [comment] 2023-10-04 15:42
@anthonychu do we have any update regarding this limitation ?

**Comment by tomkerkhove** [comment] 2024-02-08 12:32
Possible duplicate of https://github.com/microsoft/azure-container-apps/issues/592

**Comment by onionhammer** [comment] 2024-02-08 14:27
> Possible duplicate of #592

#592 is a duplicate of this

**Comment by tomkerkhove** [comment] 2024-02-08 14:29
Potato, potahto - You get what I mean :)

**Closed** 2024-02-08 14:34 UTC
Labels: enhancement, Scale
