### ISSUE TITLE
ACA Managed environment failed to initialize due to managed cluster provision failed

### ISSUE THREAD

**Issue by ezYakaEagle442** [microsoft/azure-container-apps#465] opened 2022-10-22 18:29 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Deleting an ACA environment takes more than 10 minutes, then when rerunning my Bicep code, the ACA Env. provisionning fails with : 
**Managed environment failed to initialize due to managed cluster provision failed**

ERROR: ***"status":"Failed","error":***"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[***"code":"Conflict","message":"***\r\n  \"status\": \"Failed\",\r\n  \"error\": ***\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      ***\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          ***\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"***\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": ***\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      ***\\r\\n        \\\"code\\\": \\\"OperationFailed\\\",\\r\\n        \\\"message\\\": \\\"Managed environment failed to initialize due to managed cluster provision failed\\\"\\r\\n      ***\\r\\n    ]\\r\\n  ***\\r\\n***\"\r\n          ***\r\n        ]\r\n      ***\r\n    ]\r\n  ***\r\n***"***]***

### Steps to reproduce
1. repro steps at https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv
2. run [https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/.github/workflows/deploy-iac.yml](https://github.com/ezYakaEagle442/aca-java-petclinic-mic-srv/blob/main/.github/workflows/deploy-iac.yml)

**Expected behavior** [What you expected to happen.]
the ACA Env. should be provisionned

**Actual behavior** [What actually happened.]
Workflow fails

**Screenshots**         
N/A

### Additional context
Ex. GH Workflow triggering Bicep

@kendallroden

**Comment by tklae** [comment] 2022-11-02 19:58
We are seeing the same error after even longer creation (and deletion) times of more than 1h for creation and often 20-45 minutes for a managed environment deletion.

We were trying to set up a Container App within a VNet through Terraform.

### Steps to reproduce
1. Use the terraform code at https://github.com/thomast1906/thomasthorntoncloud-examples/tree/master/Container-Apps-vnet-deployment-AzAPI-Terraform/terraform
2. Change TF variables to 
  - `location = "germanywestcentral"` (probably not important for reproduction)
  - `network_address_space     = "10.10.0.0/23"`
  - `aca_subnet_address_prefix = "10.10.0.0/23"`
3. In `main.tf` we changed the following values to avoid any conflicts with existing VNets (tbh we are not sure how these correspond with the address/subnet spaces but in the original example they also weren't within the network address space range):
```
dockerBridgeCidr       = "10.62.0.1/16"
platformReservedCidr   = "10.61.0.0/16"
platformReservedDnsIP  = "10.61.0.2"
```
4. Increase timeouts for the Container App Environment in the Terraform code (otherwise it times out in Terraform):
```
  timeouts {
    create = "2h"
    delete = "2h"
  }
```

**Expected behavior**
The ACAE is provisioned within a couple of minutes.

**Actual behavior**
After more than 1h the following error message is shown:

```
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.App/managedEnvironments/XXX\" / Api Version \"2022-03-01\")": GET https://management.azure.com/subscriptions/XXX/providers/Microsoft.App/locations/germanywestcentral/managedEnvironmentOperationStatuses/XXX
│ --------------------------------------------------------------------------------
│ RESPONSE 200: 200 OK
│ ERROR CODE: OperationFailed
│ --------------------------------------------------------------------------------
│ {
│   "id": "/subscriptions/XXX/providers/Microsoft.App/locations/germanywestcentral/managedEnvironmentOperationStatuses/XXX",
│   "name": "XXX",
│   "status": "Failed",
│   "error": {
│     "error": {
│       "code": "OperationFailed",
│       "message": "Managed environment failed to initialize due to managed cluster provision failed"
│     },
│     "code": "OperationFailed",
│     "message": "Managed environment failed to initialize due to managed cluster provision failed"
│   },
│   "startTime": "2022-11-02T14:56:55.1053903"
│ }
│ --------------------------------------------------------------------------------
│ 
│ 
│   with azapi_resource.containerapp_environment,
│   on main.tf line 32, in resource "azapi_resource" "containerapp_environment":
│   32: resource "azapi_resource" "containerapp_environment" {
│ 
```

Subscription, RG and other IDs can be provided in private.

**Comment by dbeattie71** [comment] 2022-11-02 22:37
Seeing the same issue, with Pulumi and no vNet.

```
using Pulumi.AzureNative.App.V20220601Preview;
using Pulumi.AzureNative.Resources;
using Deployment = Pulumi.Deployment;

return await Deployment.RunAsync(() =>
{
    var resourceGroup = new ResourceGroup("my-resource-group", new ResourceGroupArgs
    {
        Location = "CentralUS"
    });

    var managedEnvironment = new ManagedEnvironment("my-managed-environment", new ManagedEnvironmentArgs
    {
        ResourceGroupName = resourceGroup.Name,
        Location = resourceGroup.Location
    });
});

```

**Comment by CrunchyBlue** [comment] 2022-11-02 22:51
Experiencing the same issue using the azapi terraform provider.

**Comment by onionhammer** [comment] 2022-11-07 20:43
We are seeing the same thing, creating a container app environment via bicep with a vnet.. times out after an hour or so

**Comment by chinadragon0515** [comment] 2022-12-16 07:08
Please send sub id/rg name/env name, failed creation time to acasupport@microsoft.com, we will check. Or you can create a support ticket. thanks.

**Comment by decewei** [comment] 2023-02-07 03:29
Having the same issue. So is the current ACA only works with non custom vnet? Any best practice?

**Comment by Geertvdc** [comment] 2023-03-16 15:25
I'm having the exact same issues. With vnet i get same error as above. without vnet it does work. Any ideas?

**Comment by cachai2** [comment] 2023-05-09 17:06
Hi folks, this exception is a catch all exception, so we can't say what the exact cause is without knowing more information. It is in the backlog to provide more granularity for these exceptions, but for now, please follow @chinadragon0515's guidance.

> Please send sub id/rg name/env name, failed creation time to [acasupport@microsoft.com](mailto:acasupport@microsoft.com), we will check. Or you can create a support ticket. thanks.

**Comment by magkal** [comment] 2023-05-10 08:28
For us, this error was caused by a company wide Policy requiring tags with a specific set of values on all resource groups. Setting a temporary exempt of type waiver for the given subscription enabled the deployment of the container apps environment with vNet enabled to work.

_It wasn't obvious in the deployment error, but i managed to drill down to find the root cause in the azure portal, being a policy denied error._

**Comment by jemrpo** [comment] 2023-05-25 20:38
Had this issue and found that the issue was being caused by a policy that blocks the creation of Public IPs, which are needed for **Consumption Only Environments** https://learn.microsoft.com/en-us/azure/container-apps/networking#consumption-only-environment.

Looking forward for **Workload Profile Environments** to be GA, or available in more regions.

**Comment by simonjj** [comment] 2024-09-05 23:56
Closing this issue as we're conflating multiple issues here. If someone experiences this please open a new issue and be detailed in repro steps.

**Closed by simonjj** 2024-09-05 23:56 UTC
Labels: issue, Networking
