### ISSUE TITLE
Auth setting excluded paths gets trimmed when using cli

### ISSUE THREAD

**Issue by TonyFjo** [microsoft/azure-container-apps#464] opened 2022-10-21 13:50 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When updating a authorization setting with the az containerapp client and add excludedpath first and last character of the path is trimmed away.

### Steps to reproduce
1. Add authentication to a container app
2. Run  az containerapp auth update --excluded-paths "/api/HealthCheck" on the container app

**Expected behavior** [What you expected to happen.]
I would expect the excluded path to include "/api/HealthCheck" 

**Actual behavior** [What actually happened.]
The first and last characters are trimmed and the resulting path is "api/HealthChec"

**Screenshots**         
![image](https://user-images.githubusercontent.com/67278295/197211590-6ecf0b6a-72f5-40c3-9a8a-3c8525142366.png)

### Additional context
Cli, it does not even exist in the portal.

**Comment by anthonychu** [comment] 2022-10-25 23:57
@StrawnSC Can you please take a look? I think it's caused by [this](https://github.com/Azure/azure-cli-extensions/blob/33e409363cfffe0f09fe3256ed03e62798d80e73/src/containerapp/azext_containerapp/custom.py#L3658).

**Comment by simonjj** [comment] 2024-08-08 22:12
Assuming this has been resolved. Closing this, please reopen or open a new issue and link to this one if it still persists.

**Closed by simonjj** 2024-08-08 22:12 UTC
Labels: bug, investigating, CLI

**Comment by runeli** [comment] 2024-08-20 13:56
@simonjj this is still an issue. Just tested with 

`❯ az --version
azure-cli                         2.63.0`

**Comment by MarcoABCardoso** [comment] 2024-10-31 17:09
Just found out the CLI expects an array like the example below:
> --excluded-paths "[/path1,/path2]"
The trimming appears to be the way the CLI removes the square brackets. Tested on 2.62.0
