### ISSUE TITLE
Problems with Envoy Sidecar Container when using Jobs on Workload Profile

### ISSUE THREAD

**Issue by sch1ldkr0ete** [microsoft/azure-container-apps#939] opened 2023-10-12 17:37 UTC
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When running an Azure Container Apps Job in an Environment with a Workload Profile (Consumption Plan, own VNET with subnet size /27) we are getting problems with the Envoy Sidecar Container:
```
[2023-10-12 05:09:11.450][13][warning][main] [source/server/server.cc:794] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
```
The Job is then failing with the backoff limit:
```
Job has reached the specified backoff limit
```

### Steps to reproduce
1. Create a Container App Environemnt  (Workload Profile, Consumption Plan, own VNET, SNET size /27) via portal or via CLI
2. Create an Container App Job with the following command: `az containerapp job create  --name <name> --resource-group <rg>  --environment <cae> --trigger-type "Manual" --replica-timeout 1800 --replica-retry-limit 0 --replica-completion-count 1 --parallelism 1 --image "mcr.microsoft.com/k8se/quickstart-jobs:latest"--cpu "0.25" --memory "0.5Gi" --subscription <subscription>

**Expected behavior**
Example job would be excuted without any errors.

**Actual behavior**
Error in the Envoy Sidecar Container.

**Comment by olandese** [comment] 2023-10-13 12:03
we are having the same issue, using GH runners containers. At some point the GH Keda scaler stops working

**Comment by p-bouchon** [comment] 2023-10-13 21:03
Hi, can you please provide your subscription ID, env name, and job name so we can investigate further? We are unable to reproduce on our end, thanks.

**Comment by olandese** [comment] 2023-10-14 11:35
Hi @p-bouchon I would like to give you the information requested, but I am hesitant to give the subscription id here.
How can I share with you the information requested in a private way?

**Comment by sch1ldkr0ete** [comment] 2023-10-16 13:00
> Hi, can you please provide your subscription ID, env name, and job name so we can investigate further? We are unable to reproduce on our end, thanks.
Sent you an Email with the requested information to acasupport@microsoft.com. Hope that is correct.

**Comment by p-bouchon** [comment] 2023-10-16 14:23
Yes that is the correct email, sorry for the confusion. We will take a look

**Comment by p-bouchon** [comment] 2023-10-17 00:53
In Germany West Central our vk chart was using a slightly outdated version which caused the sidecars on jobs to not end properly when the main job container ended. We've upgraded the vk chart version of your cluster while we upgrade the rest of the region, so you should no longer be impacted

**Comment by olandese** [comment] 2023-10-18 12:46
We are having the following issue: 

[2023-10-18 12:24:14.958][14][warning][main] [source/server/server.cc:682] No admin address given, so no admin HTTP server started.

Just sent an email with the Subscription Id, App Env name etc...

> > Hi, can you please provide your subscription ID, env name, and job name so we can investigate further? We are unable to reproduce on our end, thanks.
> 
> Sent you an Email with the requested information to [acasupport@microsoft.com](mailto:acasupport@microsoft.com). Hope that is correct.

**Comment by oscarhermoso** [comment] 2023-10-19 04:03
Running into same error message, `Job has reached the specified backoff limit`

Slightly different configuration though - GitHub Container Registry, Azure Container Apps Jobs, Consumption, No VNet, Australia South-East. No sidecar container.

I've raised a MS Support request via the portal just now, should I also email [acasupport@microsoft.com](mailto:acasupport@microsoft.com)?

**Comment by oscarhermoso** [comment] 2023-10-19 10:15
> Running into same error message, `Job has reached the specified backoff limit`
> 
> Slightly different configuration though - GitHub Container Registry, Azure Container Apps Jobs, Consumption, No VNet, Australia South-East. No sidecar container.
> 
> I've raised a MS Support request via the portal just now, should I also email [acasupport@microsoft.com](mailto:acasupport@microsoft.com)?

Seems to have resolved itself a few hrs later

**Comment by vinisoto** [comment] 2023-11-22 21:23
Closing as this has been addressed via email. Please let us know if there are further questions

**Closed by vinisoto** 2023-11-22 21:23 UTC
Labels: Jobs, Fixed
