### ISSUE TITLE
"exec" causes my terminal to hide all keyboard input upon exit

### ISSUE THREAD

**Issue by duglin** [microsoft/azure-container-apps#474] opened 2022-10-31 19:28 UTC
When I exec into an ACA pod (`az containerapp exec -n echo2 -g default`) and then exit (with and w/o doing commands in the pod), back on the non-containerized terminal I can't see what I type. I think something with the "exec" CLI is setting some tty stuff and isn't resetting it before exiting. So, for this flow:
- az containerapp exec -n echo2 -g default
- exit (in the pod and you can see that right before the "INFO" line)
- hit enter a few times now that I'm back at the normal terminal, and I see this (notice each prompt is on the same line and you can't see that I typed "exit" but you can see the "logout" that the system echo'd):
```
[dev]root@dev:~$ az containerapp exec -n echo2 -g default
INFO: Connecting to the container 'c1'...
WARNING: Use ctrl + D to exit.
INFO: Successfully connected to container: 'c1'. [ Revision: 'echo2--iq63mpt', Replica: 'echo2--iq63mpt-7d6fb6c777-tn9zx']
/ # exit
INFO: received success status from cluster
WARNING: Disconnecting...
[dev]root@dev:~$ [dev]root@dev:~$ [dev]root@dev:~$ logout
Connection to dev closed.
```

**Comment by anthonychu** [comment] 2022-11-02 16:19
@StrawnSC can you please take a look?

**Comment by duglin** [comment] 2022-11-02 16:22
I should mention, my CLI is on Linux/Ubuntu.

**Comment by duglin** [comment] 2023-01-06 15:51
@strawnSC any update on this? It's kind of annoying having to kill my terminal after each 'exec'

**Comment by StrawnSC** [comment] 2023-02-02 00:50
Hey @duglin, sorry for the delay here. I was able to repro this earlier but couldn't figure out the root cause (as far as I could tell, we were resetting all the TTY settings we set to make ssh work). I no longer work on ACA CLI, but let me see if I can get someone assigned to this

**Comment by sebastien-coavoux** [comment] 2023-04-26 16:27
For people impacted, in addition to the good old `reset`  command from bash,  you can also do `stty echo` to avoid loosing the scroll you had in the terminal

**Comment by duglin** [comment] 2023-05-03 21:56
Any update on this one?  @anthonychu

**Closed** 2024-08-29 22:51 UTC
Labels: bug, CLI

**Comment by sebastien-coavoux** [comment] 2024-08-31 01:24
What was done to consider this as completed @simonjj ? Any link to a commit or PR ?
