### ISSUE TITLE
Dedicated environments can no longer resolve dns over tcp

### ISSUE THREAD

**Issue by madsBR** [microsoft/azure-container-apps#842] opened 2023-07-18 17:39 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ X] regression (a behavior that used to work and stopped in a new release)

### Issue description
Apps on environments on the dedicated plan will no longer resolve dns over TCP.

### Steps to reproduce
1. Create a dedicated environment.
2. Deploy e.g. ubuntu:20.04 image
3. get a terminal ssh from portal and execute
`$dig +tcp microsoft.com`

**Expected behavior** [What you expected to happen.]
It resolves DNS
**Actual behavior** [What actually happened.]
It returns
`communications error to 127.0.0.11#53: end of file`
The  127.0.0.11 namespace seems to be a dedicated feature.

We are positive that this is not a problem on non-dedicated enviroments. We are 90% certain that this has worked previously on dedicated environments
```[tasklist]
### Tasks
```

**Comment by madsBR** [comment] 2023-07-19 09:06
I see this has been marked  "bug" + "in Progress". Is there any ETA on resolving?

**Comment by torosent** [comment] 2023-07-20 21:57
I don't have exact date yet but we are activity working on it.

**Comment by madsBR** [comment] 2023-07-24 12:50
Thanks man,
The issue for our applications arises for specific DNS addresses, where resolving (via UDP) leads to an answer like

`;; Truncated, retrying in TCP mode.`
and then the error  mentioned in thread.
`communications error to 127.0.0.11#53: end of file`

It happens to be that an address important to our application gives that response. Is there a hack/ work-around which one could implement in the mean time to avoid it retrying to resolve in TCP ?

**Comment by njuCZ** [comment] 2023-07-26 02:17
Hi @madsBR, the issue is: according to RFC for dns, the udp dns query can support largest approximately 464 bytes for dns query answer. If the response is exceed the size, it will retry in tcp mode. And currently tcp is not supported.

The fix is ready and we plan to deploy it within a month. Once all region is ready we will reply in this thread again.

**Comment by mortenf1984** [comment] 2023-08-15 05:47
Not sure if this is related, but it seems, Recently (Since Friday afternoon i believe), my container apps are not resolving private DNS records against our DNS servers. The setup is Consumption on Workload Profile edition, vNet internal with UDR to Azure Firewall. Subnet is set up correctly and it was working, DNS for Private Link resources worked, internal services with DNS worked, but now I get error in starting the container because it tries to contact the public side of the resources but this is disabled.

Could this be related?

**Comment by njuCZ** [comment] 2023-08-16 06:53
@mortenf1984, can you DM me your container app resource id so I could take a check?

**Comment by njuCZ** [comment] 2023-08-16 06:54
@madsBR the tcp support is ready in all regions, could you take a try again?

**Comment by madsBR** [comment] 2023-08-17 10:13
> Hi @madsBR the tcp support is ready in all regions, could you take a try again?

Hi looks promising did initial tests. Will return next week with final confirmation that it solves our specific DNS problem too.

**Comment by madsBR** [comment] 2023-08-21 11:04
It works! Thanks

**Comment by njuCZ** [comment] 2023-08-23 02:36
Hi @madsBR, could you help close this issue?
> It works! The bug has been resolved in our use case. Thanks!

@mortenf1984 If you still have issue, you could send detail info to acasupport#microsoft.com and we will take a look

**Closed** 2023-08-23 08:14 UTC
Labels: bug, In progress
