### ISSUE TITLE
Feature Request: SSH login and access settings for debugging

### ISSUE THREAD

**Issue by YuKogasaka** [microsoft/azure-container-apps#146] opened 2022-03-24 01:17 UTC
**Is your feature request related to a problem? Please describe**.  
In Azure Container Apps (ACA) integrated Custom VNet, ACA wants to check if communication between other Azure services (e.g. Azure Database) is via VNet.

**Describe the solution you'd like**.    
For that my purpose, I want to feature that use SSH login (like Azure Container Apps for Linux) to ACA.

**Describe alternatives you've considered**.   
I have installed curl and phpmyadmin on ACA and checked it, but it is necessary to prepare a container for communication check, and it takes time to check the communication status from Log Analytics.

**Comment by anthonychu** [comment] 2022-03-26 16:32
We're working on the ability to connect to a console in a container #54. You'll be able to connect to the container and run commands from the Azure portal, Azure CLI, and other supported clients. Would that work?

**Comment by anthonychu** [comment] 2022-04-14 17:12
Closing as duplicate of #54.

**Closed by anthonychu** 2022-04-14 17:12 UTC
Labels: enhancement
