### ISSUE TITLE
Experiencing cold start even when probes are set (single-revision)

### ISSUE THREAD

**Issue by hamenu** [microsoft/azure-container-apps#598] opened 2023-01-25 03:14 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have deployed a .netcore app on a _single-revision_ container app with only _one container_ and _min-replica of 1_.

My app doesn't have separate endpoints for startup/readiness/liveness. So, I'm just using a single `/version` endpoint for all 3 which simply returns the value of `Environment.GetEnvironmentVariable("CONTAINER_APP_REVISION")` plus assembly version and commit info. I hit this endpoint in my browser to see what revision is getting traffic.

The probes are set as follows:
```
STARTUP
  path: /version
  timeoutSeconds: 15
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

READINESS
  path: /version
  timeoutSeconds: 10
  periodSeconds: 5
  successThreshold: 1
  failureThreshold: 3

LIVENESS
  path: /version
  timeoutSeconds: 5
  periodSeconds: 3
  successThreshold: 1
  failureThreshold: 3
```
Imagine the existing revision is `revision--a`, therefore the `/version` endpoint returns `revision--a` in milliseconds time (as it's already warmed up and there is one replica always running), and the new revision being created is `revision--b`.

I keep refreshing the `/version` page in the browser. I keep seeing `revision--a` as expected. Once I create the new revision, the revision becomes provision**ing** in Azure Portal and:

**Actual behavior** [What actually happened.]
straightaway, the `/version` endpoint slows down to seconds, like 5 seconds, and after 5 seconds I see `revision--b` in the response.
If I were to show a timeline with the response, it would be:
```
hh:mm:ss.sss
10:00:00.200 -> revision--a
10:00:00.400 -> revision--a
10:00:00.600 -> revision--a
  the new revision is created here; the endpoint doesn't return anything for 5 seconds (spinner spinning in the browser)
10:00:05.000 -> revision--b
```

**Expected behavior** [What you expected to happen.]
1. The `/version` endpoint should keep returning `revision--a` between the time window of `10:00:00.600 - 10:00:05.000` _without any slowness_ while the new revision in provision**ing**.
2. Once the revision is provision**ed** successfully, the endpoint should return `revision--b`, _still without any slowness_

I have read these two relevant issues already:

* https://github.com/microsoft/azure-container-apps/issues/244
  * I will add a comment in the issue that the new revision still receives 100% of the traffic - so it's still a bug I guess as far as that issue is concerned
  * Even though the Portal shows 100% of the traffic being redirected to the provision**ing** revision, i.e. `revision--b`, I experience no downtime on the `/version` endpoint - not sure if 'no response/being stuck for 5 seconds' is considered a 'downtime' or 'cold start' 🤷‍♀️
* https://github.com/microsoft/azure-container-apps/issues/199
  * I have a min-replica of 1, so that single replica should still be warmed up and return `revision--a` while `revision--b` is provision**ing**.
  * Since I'm using the same endpoint for startup and manual browser validation, the `/version` endpoint should almost immediately return `revision--b` when the traffic is switched on to it.

### Steps to reproduce
1. Create a single-revision container app with only one container in it
2. Deploy an app (mine was .netcore 6.0 but probably shouldn't matter)
3. Create a sample endpoint that returns the value of `CONTAINER_APP_REVISION` environment variable
   * You can optionally put a `Task.Delay()`, `setTimeout()` or something if you want to make the situation more obvious
4. Set up the probes as above
5. Keep hitting `/version` endpoint, either in the browser or automated
6. Create a new revision in Azure Portal
7. Observe that once the new revision is created, while still provision**ing**,
   * You don't receive a response from your endpoint even returning the old revision value
   * After a cold start, you'll see the new revision name

**Screenshots**         
Here is the steps I follow in Azure Portal when creating a new revision:
![image](https://user-images.githubusercontent.com/123523199/214468646-9a47d7c7-f4a5-43ae-ab20-dd47e3e43fb1.png)

I wasn't sure whether I should select the checkbox at number 2, so I tried having it selected and not selected. The cold start experience was more consistent when unchecked, but sometimes with checked too.

And here is what revision management page shows when I create the revision:
![image](https://user-images.githubusercontent.com/123523199/214469428-7b7a5142-c28f-4015-94ec-86d0c6f2f452.png)

### Additional context
I use Pulumi to provision the infrastructure, but regardless of how you end up with the infrastructure in Azure, I use the following Azure CLI command to update the image, and still experience the exact same cold start explained:

```
latest_revision_name=$(az containerapp update --resource-group <resource-group> --name <container-app-name> --image <image-from-azure-container-registry> --query 'properties.latestRevisionName' --output tsv)
```
Or even with the additional parameter of `--container-name <my-container-name>` which is not well documented.

And this is the script I use to see the status of the new revision from the `update` command above:

```
az containerapp revision show --resource-group <resource-group> --name <container-app-name> --revision $latest_revision_name --query '{ active: properties.active, healthState: properties.healthState, provisioningState: properties.provisioningState, trafficWeight: properties.trafficWeight }'
```
While the new revision is provision**ing**, I see this output:

```
{
  "active": true,
  "healthState": "None",
  "provisioningState": "Provisioning",
  "trafficWeight": 100
}
```

**Comment by schafei** [comment] 2023-02-09 15:58
I'm experiencing something similar, although for me, the zero downtime deployment seems to work in ~50% of the times. In the other ~50% of cases, the app is not reachable anymore during provisioning of the new revision. Because our app takes a long time (around 3min) to pass its probes in the prod environment, this is quite an issue and prevents of from usage of the container apps for other use cases.
We are using Terraform and the AzApi Provider to deploy our container apps. Not sure, if that makes any difference.

**Comment by hamenu** [comment] 2023-02-12 22:53
Ah yes, @schafei is right - it's like 50-50. Still the new revision _always_ shows active and receiving 100% of the traffic in Azure Portal while it's provision**ing**, but the `/version` endpoint is the 50-50 case where sometimes it returns the old version without any slowness, while sometimes it becomes non-responsive while the new revision is provisioning.

**Comment by anthonychu** [comment] 2023-03-14 22:05
@ahmelsayed Can you please take a look at this?

**Comment by SophCarp** [comment] 2023-03-14 22:42
Fix is in progress! It should be out in April

**Comment by SophCarp** [comment] 2023-03-28 19:03
Bug should be released everywhere. Closing the issue, please let me know if the issue is comes up again!

**Closed by SophCarp** 2023-03-28 19:03 UTC
Labels: bug, Provisioning, In progress
