### ISSUE TITLE
Outbound http timeouts (SNAT)

### ISSUE THREAD

**Issue by wynandjordaan** [microsoft/azure-container-apps#517] opened 2022-12-02 21:34 UTC
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I started migrating to Container Apps from Azure functions and today I observed that the token requests from the Container to our Identity Server started timing out. Even though the server can issue tokens consistently under 200ms. I am seeing timeouts from 100sec. 

At this point my container was scaled to 30 instances and there was about 2000 messages waiting in the Service Bus queue.

### Steps to reproduce
1. Large number (2000+) of service bus messages to be processed in the queue.
2. A service bus handler that has to request a token to an outside service via HTTP.

**Expected behavior** [What you expected to happen.]
Once the messages are being processed a token is requested and received from the service. The message is then discarded based on config.
I don't expect the timeouts as the identity service was issuing tokens. It feels like the container is not capable of processing the responses and then times out.

**Actual behavior** [What actually happened.]
The token request times out after 100 seconds, and an exception is thrown.

**Comment by kendallroden** [comment] 2022-12-08 21:43
Can you provide any insight into how your code is retrieving the token and what type of token store you are using?

**Comment by wynandjordaan** [comment] 2022-12-09 08:04
Hi Kendall,

I have found the issue. It looks like I am running out of SNAT ports.

From what I have read about it - one way to have additional SNAT ports is to use a NAT Gateway. But if I enable the NAT gateway on the VNet, then it disabled the access to the service.

Do you have any other suggestions that I can try?

**Comment by kendallroden** [comment] 2022-12-13 17:35
Hey @wynandjordaan sometimes high SNAT usage can be caused by code not re-using connections, but we can also bump up their outbound IP count, by default now envs only get 1. The challenge is that if a new env gets created you would have to re-request so not ideal.

**Comment by wynandjordaan** [comment] 2022-12-13 17:50
Hi Kendall

Thanks for your answer.

We are using all the best practices as far as I know with HttpClient and all our outbound other connections. 

I was able today to simulate the SNAT starvation easily with a servicebus listener opening a http connection. 

I have tried to optimize our code by reusing http clients, but it seems that I always hit the limits. From what I understood from the Vnet with a NAT gateway is that it will give us 64k outbound connections, but as soon as I enable this the inbound connections are not allowed. 

We are using Azure function images on ACA - just for your information. 

How many outbound connections will we have with 2 IPs? If that significantly increases our usable ports then we can go this route. 

Is there any other solution that we can consider? 

Kind regards.

**Comment by SophCarp** [comment] 2023-02-24 18:25
Hi @wynandjordaan! I'm going to close this issue for now, since its old. Apologies for the late response. If you are still experiencing issues like this, please open a support ticket, and we can increase the number of IPs for you. 

Additionally, you can monitor your Snat connection and allocation of a container app. In portal, go to your container app. Inside blade, select "Diagnose and solve problems" (fourth option from the top). In that page, there's a section called "Availability and performance". Within that section, the bottom option is your SNAT connection and port allocation page. 

Hope this helps! If the resources I provided above aren't helpful, feel free to open this issue again and let me know.

**Closed by SophCarp** 2023-02-24 18:25 UTC
Labels: documentation, question, issue, Needs: triage :mag:, Networking
