### ISSUE TITLE
Connection refused when calling sidecar

### ISSUE THREAD

**Issue by vidarkongsli** [microsoft/azure-container-apps#331] opened 2022-08-01 06:32 UTC
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have a service written in .NET 6 using the Dapr SDK, which when deployed to Azure Container Apps is unable to reach the sidecar. The application works on my development workstation.

### Steps to reproduct
1. The application is deployed using a Bicep template, with the following `dapr` settings:
   * enabled: true
   * appId: app-admin
   * appProtocol: http
   * appPort: 5032
2. The following environment variables are set:
   * DAPR_HTTP_PORT: 3500
   * DAPR_GRPC_PORT: 3500
 
**Expected behavior**
The app should be able to load the state via the sidecar with the call `_daprClient.GetStateAsync<ICollection<string>>(STORE_NAME, KEY)`.

**Actual behavior** [What actually happened.]
The application throws an exception with the inner exception message: `---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:3500) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:3500)`

**Comment by anthonychu** [comment] 2022-08-04 06:27
Looks like the problem was caused by:

> 2. The following environment variables are set:
>     DAPR_HTTP_PORT: 3500
>     **DAPR_GRPC_PORT: 3500**

You don't need to set these variables. When Dapr is enabled in the container app, these variables are automatically injected with the port values that the Dapr sidecar is using. Remove the variables from your app and try again.

**Comment by vidarkongsli** [comment] 2022-08-04 09:04
> Looks like the problem was caused by:
> 
> > 2. The following environment variables are set:
> >    DAPR_HTTP_PORT: 3500
> >    **DAPR_GRPC_PORT: 3500**
> 
> You don't need to set these variables. When Dapr is enabled in the container app, these variables are automatically injected with the port values that the Dapr sidecar is using. Remove the variables from your app and try again.

Thanks for the tip. When removing the aforementioned environment variables, the same error occurs, but only trying a different port: `       ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused (127.0.0.1:50001) SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:50001)`. 

It seems that the port number for the sidecar is not correctly injected.

**Comment by anthonychu** [comment] 2022-08-04 14:46
Looks like it’s using the correct gRPC port now but there might be an issue with the sidecar. @kendallroden Do you have any troubleshooting tips?

**Comment by vidarkongsli** [comment] 2022-08-09 09:46
It might be related, but could you clarify for what the `dapr.appProtocol` is used? (Ref. https://docs.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep#dapr) The docs state that it "Tells Dapr which protocol your application is using. Valid options are http and grpc. Default is http". I interpret this so that it sets what protocol the application uses for accepting traffic from the dapr side car. But does it have an effect the other way, so that it sets the protocol that the dapr sidecar uses for accepting traffic from the application?

**Comment by vidarkongsli** [comment] 2022-08-28 07:31
It seems that this problem was caused by a misconfiguration of a pub-sub component in the environment.
Setting `initTimeout: '5s'` in a pub sub component seems to be illegal. (Works well on a state component).

```
  resource daprPubSubComponent 'daprComponents@2022-03-01' = {
    name: 'X-pub-sub'
    properties: {
      componentType: 'pubsub.azure.servicebus'
      initTimeout: '5s'
   }
}
```
Once I removed this setting from the bicep template and redeployed, the problem went away.

**Comment by kendallroden** [comment] 2022-09-14 18:30
will explore if we can document

**Comment by awachat** [comment] 2023-02-14 13:01
I am also facing the same error when using python sdk.

**Comment by SophCarp** [comment] 2023-02-28 21:32
@greenie-msft could you look into this?

**Comment by anthonychu** [comment] 2023-02-28 21:33
@awachat Can you confirm if you're having the same configuration issue as @vidarkongsli or some other issue that results in the sidecar not accepting connections?

**Comment by ihamza-shah** [comment] 2023-05-23 11:42
I have removed Dapr from my application/docker as we're not using it. 
Once, i removed it and set build command in package json, while running i'm getting "Error: Error: connect ECONNREFUSED 127.0.0.1:3500"  . Also, i'm fetching secrets while dapr runs' from "http://localhost:3500/secrets/awssecretmanager"

**Comment by simonjj** [comment] 2024-09-05 23:46
Closing this as it seems solved via docs.

**Closed by simonjj** 2024-09-05 23:46 UTC
Labels: documentation, Dapr
