### ISSUE TITLE
Feature Request: Support for init containers

### ISSUE THREAD

**Issue by mortenbock** [microsoft/azure-container-apps#130] opened 2022-03-07 18:39 UTC
**Describe the solution you'd like**.    
When deploying a new version of an app, we sometimes need to do some mandatory prep work before the main container can function, such as running SQL migrations or similar. In regular kubernetes an init container (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) is a way to do this, and ensure that if the init container does not run to completion for some reason, then the main container is not started. This option would be nice to have in ACA as well.

**Describe alternatives you've considered**.   
Migrations could be run at startup of the main container, but you may not be in charge of that image.
They could also be run as a regular "sidecar", but this could cause a race condition where the main container fails before migrations have been run.

**Comment by onionhammer** [comment] 2022-03-07 19:16
It would be **incredibly** useful to be able to do this for migrations.

**Comment by kendallroden** [comment] 2022-03-09 03:23
Hi @mortenbock - thanks for your request. I wanted to provide an alternative solution in the meantime. You can run a container app that does your migration and then set the scale down to 0 and the container app will not be billed after the initial run and scale down. I know this is not a perfect solution but I just wanted to let you know it's possible as a work around. Check out this [example]([bootstrapper.bicep](https://github.com/Azure/reddog-containerapps/blob/main/deploy/bicep/modules/container-apps/bootstrapper.bicep)). This is a "bootstrapper" that seeds our sql database in the sample.

**Comment by SophCarp** [comment] 2023-01-30 20:04
Organizing the roadmap. The roadmap issue is #606

**Comment by corwestermaniddink** [comment] 2023-03-21 07:45
We use a Readiness probe for this, but a init container would be nice :)

**Comment by alicyn** [comment] 2023-05-06 02:10
@SophCarp It looks like Init Containers is in public preview now? https://learn.microsoft.com/en-us/azure/container-apps/containers#init-containers

**Comment by anthonychu** [comment] 2023-05-08 22:26
@alicyn Yes the feature is public preview starting this week.

**Comment by jurepurgar** [comment] 2023-05-16 13:30
@anthonychu It looks great. However, it seems that init container does not have access to user assigned managed identity assigned to container app. Is this by design? In my case, I have init container that performs EF DB migrations. User assigned managed identity is used to connect to the DB from the app, and we would like to have a possibility to use the same identity for init container.

**Comment by michaelp** [comment] 2023-06-28 19:36
@mortenbock @kendallroden The proposed solution of a dedicated "init" app might be improved if we slightly change the approach. (We still need to solve the problem of concurrent migrations running from multiple instances in CI/CD) 
* [preview feature] - A dedicated  [Job](https://learn.microsoft.com/en-ca/azure/container-apps/jobs?tabs=azure-cli)  should deploy the migrations (trigger is done via ARM or via CI/CD pipeline)
* [preview feature] - An init container needs to suspend the deployment of the revision (in the "initializing state" )until the job is executed (and not to contain any actual migrations) 

As an outcome, we should get a robust and simple workflow.

**Closed** 2024-10-25 21:18 UTC
Labels: enhancement, Roadmap Related

**Comment by onionhammer** [comment] 2024-10-25 22:27
@curib note it's not possible to update init containers via the CLI

**Comment by curib** [comment] 2024-10-28 23:51
@onionhammer, you can only update init containers using YAML, not via Azure CLI parameters.
