### ISSUE TITLE
aad pod identity (MIC)

### ISSUE THREAD

**Issue by dariuszbz** [microsoft/azure-container-apps#88] opened 2022-01-31 10:44 UTC
Any plans to enable containers with aad manage identity for pods:

https://github.com/Azure/aad-pod-identity

**Comment by torosent** [comment] 2022-01-31 22:14
We are working on managed identity, and it will be released in the coming weeks.

**Comment by torosent** [comment] 2022-02-01 00:18
Duplicate of #16

**Closed by torosent** 2022-02-01 00:18 UTC

**Comment by dariuszbz** [comment] 2022-02-01 09:50
Hi @torosent! It is a great news.

Can we see e2e roadmap, please?
